name: calculator
description: "A Basic Calculator"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.6
  get_storage: ^2.1.1
  flutter_screenutil: ^5.9.0
  math_expressions: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  fonts:
   - family: MyFlutterApp
     fonts:
       - asset: assets/fonts/MyFlutterApp.ttf
   - family: RobotoSlab
     fonts:
       - asset: assets/fonts/RobotoSlab-Regular.ttf

